name: Build Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch: # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Install dependencies
      run: npm ci
      
    - name: Build web assets
      run: npm run build

    # 🔎 Debug: show repo structure
    - name: Debug – List files
      run: ls -R

    # 🔥 Fix invalid Lovable App ID automatically
    - name: Fix Capacitor App ID
      run: |
        echo "Fixing invalid App ID..."
        FILE=$(find . -name "capacitor.config.json" | head -n 1)
        if [ -z "$FILE" ]; then
          echo "❌ capacitor.config.json not found!"
          exit 1
        fi
        sed -i 's/"appId": "app.lovable.*"/"appId": "com.lovable.reelysaveit"/' "$FILE"
        sed -i 's/"appName": ".*"/"appName": "Reely Save It"/' "$FILE"
        echo "✅ Patched App ID and App Name in $FILE"
        cat "$FILE"
      
    - name: Add Android platform
      run: npx cap add android
      
    - name: Sync Capacitor
      run: npx cap sync android
      
    - name: Grant execute permission for gradlew
      run: chmod +x android/gradlew
      
    - name: Build Android APK
      run: |
        cd android
        ./gradlew assembleDebug --stacktrace
        
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: reely-save-it-debug
        path: android/app/build/outputs/apk/debug/app-debug.apk
        retention-days: 30
        
    - name: Build Release APK (unsigned)
      run: |
        cd android
        ./gradlew assembleRelease --stacktrace
        
    - name: Upload Release APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: reely-save-it-release-unsigned
        path: android/app/build/outputs/apk/release/app-release-unsigned.apk
        retention-days: 30